<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enhartt.Domain\Enhartt.Domain.csproj" />
  </ItemGroup>

<!-- Referencias a las DLLs corporativas de la carpeta Libs -->
<ItemGroup>

    <Reference Include="Magna.Cosma.Autotek.Autentificacion.Library">
      <HintPath>..\Libs\Autotek.Autentificacion.Library.dll</HintPath>
    </Reference>
    <Reference Include="Magna.Cosma.Autotek.Log">
      <HintPath>..\Libs\Autotek.Log.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>